name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**'
env:
  FORCE_COLOR: 1
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5
      - name: Install earthly
        uses: Luet-lab/luet-install-action@v1
        with:
          repository: quay.io/kairos/packages
          packages: utils/earthly
      - name: Run Lint checks
        run: |
          earthly +lint
